"""empty message

Revision ID: cc38d82b23cc
Revises: e3ddce9582fa
Create Date: 2023-12-17 02:56:02.264216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc38d82b23cc'
down_revision = 'e3ddce9582fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements_to_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idBulk', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elements_to_process')
    # ### end Alembic commands ###
